version: '3.8'

services:
  redis:
    image: redis:7.4
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
